server:
  port: 9092
spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:users}
      username: ${MONGODB_USER:Kharkiv_student}
      password: ${MONGODB_PASS:Glory_to_Ukraine}
      autoIndexCreation: true
